//! Five-card lookup tables, generated by `build.rs` into `OUT_DIR`.
//!
//! `HAND_RANKS` is keyed by the base-five rank-multiset key and `FLUSH_RANKS`
//! by a thirteen-bit rank mask for one suit; both yield a score in one dense
//! numbering where lower is better. See `build.rs` for the generator.
include!(concat!(env!("OUT_DIR"), "/hand_rank_table.rs"));
