//! Conversions between `FastHandRank` scores and `HighHandRank`, generated by
//! `build.rs` into `OUT_DIR` from the same ordering that produced the tables.
include!(concat!(env!("OUT_DIR"), "/rank_translation.rs"));
